version: '3'

services:
  image_service_server:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - "./.env:/app/.env"
      - "${IMAGE_STORAGE_PATH}:/app/image_storage"
      - "${VIDEO_STORAGE_PATH}:/app/video_storage"
      